@startuml model
hide empty members

enum Status {
    TODO
    PROGRESS
    DONE
}

enum Priority {
    "1: Emergency & Important for you"
    "2: Important for you"
    "3: Emergency"
    "4: Not your job"
}

class ProjectRoot {
    -filepath : String

    +{static}load() : void
    -{static}import_dict_obj_from_json() : List[ProjectDict]
    -{static}restore_from_dict(dict:List[ProjectDict]) : ProjectRoot
    +save() : void
    -export_dict_as_json() : None
    -export_as_dict() : List<ProjectDict>
}

abstract class ABC_Tree {
    -id     : UUID
    +children : List<ABC_Tree>

    +id() : UUID
    +getChildren() : List<ABC_Tree>
    +getChildbyID(id:UUID) : ABC_Tree
    +createChild() : ABC_Tree
    +deleteChild(id:UUID) : void
    ' I/Oに関する部分
    +{static}{abstract} restoreFromDict(dict:Union[ProjectDict, TaskDict]) : ABC_Tree
    +{abstract} exportAsDict() : Union[ProjectDict, TaskDict]
}

abstract class ABC_PnT {
    +name   : String
    +due    : Date
    +status : Status
    +memo   : String
}


class Project {
}

class Task {
    +assignee   : String
    +estimation : String
    +priority   : Priority
}

ProjectRoot "1" *-down- "0...*" Project
Project "1" *-down- "0...*" Task
ABC_Tree <|-- ABC_PnT
ABC_Tree <|- ProjectRoot
ABC_PnT <|- Project
ABC_PnT <|- Task
@enduml